version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: petsbook-nginx-prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./public:/var/www/html/public
      - ./docker/nginx/nginx.prod.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - php
    networks:
      - petsbook-network

  php:
    env_file:
      - .env.production
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: petsbook-php-prod
    volumes:
      - ./src:/var/www/html/src
      - ./public:/var/www/html/public
      - ./vendor:/var/www/html/vendor
      - ./composer.json:/var/www/html/composer.json
      - ./composer.lock:/var/www/html/composer.lock
      - ./.env.production:/var/www/html/.env
      - ./logs:/var/www/html/logs
    environment:
      - APP_ENV=production
      - GOOGLE_TRANSLATE_API_KEY=${GOOGLE_TRANSLATE_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - MAIL_DRIVER=${MAIL_DRIVER}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
    networks:
      - petsbook-network

networks:
  petsbook-network:
    driver: bridge