services:
  nginx:
    image: nginx:alpine
    container_name: petsbook-nginx-prod
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./public:/var/www/html/public
      - ./docker/nginx/nginx.prod.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - php
    networks:
      - petsbook-network

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: petsbook-php-prod
    restart: unless-stopped
    env_file:
      - .env.production
    volumes:
      - ./src:/var/www/html/src
      - ./public:/var/www/html/public
      - ./vendor:/var/www/html/vendor
      - ./composer.json:/var/www/html/composer.json
      - ./composer.lock:/var/www/html/composer.lock
      - ./.env.production:/var/www/html/.env
      - ./logs:/var/www/html/logs
      - ./translate-task.php:/var/www/html/translate-task.php
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:-https://site.petsbook.ca,http://64.188.10.53,http://site.petsbook.ca}      
    networks:
      - petsbook-network

networks:
  petsbook-network:
    driver: bridge