services:
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: petsbook-php
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html/src
      - ./public:/var/www/html/public
      - ./logs:/var/www/html/logs
      - ./vendor:/var/www/html/vendor
      - ./composer.json:/var/www/html/composer.json
      - ./composer.lock:/var/www/html/composer.lock
      - ./.env:/var/www/html/.env
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - APP_ENV=${APP_ENV:-development}
      - APP_DEBUG=${APP_DEBUG:-true}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:-http://localhost:5173,http://127.0.0.1:5173}
    networks:
      - petsbook-network

  nginx:
    image: nginx:alpine
    container_name: petsbook-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/html/public
      - ./logs:/var/log/nginx
      - /etc/letsencrypt/live/64.188.10.53.nip.io:/etc/letsencrypt/live/64.188.10.53.nip.io:ro
      - /etc/letsencrypt/archive/64.188.10.53.nip.io:/etc/letsencrypt/archive/64.188.10.53.nip.io:ro
    depends_on:
      - php
    networks:
      - petsbook-network

networks:
  petsbook-network:
    driver: bridge