version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: petsbook-mysql-prod
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/migrations:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - petsbook-network
    command: --default-authentication-plugin=mysql_native_password

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: petsbook-php-prod
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html/src
      - ./public:/var/www/html/public
      - ./logs:/var/www/html/logs
      - ./vendor:/var/www/html/vendor
      - ./composer.json:/var/www/html/composer.json
      - ./composer.lock:/var/www/html/composer.lock
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    depends_on:
      - mysql
    networks:
      - petsbook-network

  nginx:
    image: nginx:alpine
    container_name: petsbook-nginx-prod
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/nginx.prod.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/html/public
      - ./logs:/var/log/nginx
    depends_on:
      - php
    networks:
      - petsbook-network

volumes:
  mysql_data:

networks:
  petsbook-network:
    driver: bridge 